"""add lat lng to farmacias

Revision ID: 75640f263e92
Revises: 84a4e55d19a1
Create Date: 2025-09-09 10:27:43.234040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75640f263e92'
down_revision = '84a4e55d19a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
