"""Agregar columna farmacia_id a medicamento

Revision ID: 76c74eb8dc61
Revises: 9c5ebaaf63b7
Create Date: 2025-08-31 16:52:44.120214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c74eb8dc61'
down_revision = '9c5ebaaf63b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmacias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmacia_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'farmacias', ['farmacia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('farmacia_id')

    op.drop_table('farmacias')
    # ### end Alembic commands ###
