"""empty message

Revision ID: 9c5ebaaf63b7
Revises: 
Create Date: 2025-07-16 12:48:02.439981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5ebaaf63b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atc_class',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['parent_code'], ['atc_class.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('medicamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_local', sa.String(length=255), nullable=False),
    sa.Column('forma_farmaceutica', sa.String(length=100), nullable=True),
    sa.Column('concentracion', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicamento_atc',
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('atc_code', sa.String(length=10), nullable=False),
    sa.Column('indicacion_local', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['atc_code'], ['atc_class.code'], ),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamento.id'], ),
    sa.PrimaryKeyConstraint('medicamento_id', 'atc_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicamento_atc')
    op.drop_table('medicamento')
    op.drop_table('atc_class')
    # ### end Alembic commands ###
